export const pipedreamApps24 = [
  {
    id: 'app_mWnhBo',
    nameSlug: 'openai',
    name: 'OpenAI (ChatGPT)',
    authType: 'keys',
    description:
      'OpenAI is an AI research and deployment company with the mission to ensure that artificial general intelligence benefits all of humanity. They are the makers of popular models like ChatGPT, DALL-E, and Whisper.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_mWnhBo/logo/orig',
    customFieldsJson:
      '[{"name":"api_key","label":"API Key","description":"[Create a new API key](https://platform.openai.com/account/api-keys) in your OpenAI account and enter it here.","default":null,"optional":null,"type":"password"}]',
    categories: ['Artificial Intelligence (AI)'],
    featuredWeight: 1000000099,
    connect: {
      allowed_domains: ['api.openai.com'],
      base_proxy_target_url: 'https://api.openai.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_X7Lhxr',
    nameSlug: 'notion',
    name: 'Notion',
    authType: 'oauth',
    description: "Notion is a new tool that blends your everyday work apps into one. It's the all-in-one workspace for you and your team.",
    imgSrc: 'https://assets.pipedream.net/s.v0/app_X7Lhxr/logo/orig',
    customFieldsJson: '[]',
    categories: ['Productivity'],
    featuredWeight: 1000000099,
    connect: {
      allowed_domains: ['api.notion.com'],
      base_proxy_target_url: 'https://api.notion.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_168hvn',
    nameSlug: 'google_sheets',
    name: 'Google Sheets',
    authType: 'oauth',
    description: 'Use Google Sheets to create and edit online spreadsheets. Get insights together with secure sharing in real-time and from any device.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_168hvn/logo/orig',
    customFieldsJson: '[]',
    categories: ['Productivity'],
    featuredWeight: 1000000098,
    connect: {
      allowed_domains: ['www.googleapis.com', 'sheets.googleapis.com'],
      base_proxy_target_url: 'https://sheets.googleapis.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_1dBhqA',
    nameSlug: 'anthropic',
    name: 'Anthropic (Claude)',
    authType: 'keys',
    description: 'AI research and products that put safety at the frontier. Introducing Claude, a next-generation AI assistant for your tasks, no matter the scale.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_1dBhqA/logo/orig',
    customFieldsJson:
      '[{"name":"api_key","label":"API Key","description":"Navigate to your [Anthropic account settings](https://console.anthropic.com/account/keys) to generate an API key then paste it here","default":null,"optional":null,"type":"password"}]',
    categories: ['Artificial Intelligence (AI)'],
    featuredWeight: 1000000098,
    connect: {
      allowed_domains: ['api.anthropic.com'],
      base_proxy_target_url: 'https://api.anthropic.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_OD5hL6',
    nameSlug: 'telegram_bot_api',
    name: 'Telegram',
    authType: 'keys',
    description: 'Telegram, is a cloud-based, cross-platform, encrypted instant messaging (IM) service.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_OD5hL6/logo/orig',
    customFieldsJson:
      '[{"name":"token","label":"Bot Token","description":"To use the [Telegram Bot API](https://core.telegram.org/bots/api), you must first [create a new bot](https://core.telegram.org/bots#6-botfather) by chatting with the **BotFather**.\\n\\n\\u003cbr /\\u003e\\n\\u003cimg width=\\"400px\\" src=\\"https://res.cloudinary.com/pipedreamin/image/upload/v1659658124/connected_account_instructions/2022-08-04_17.07.43_mhxpvq.gif\\" alt=\\"Telegram Bot how to\\" /\\u003e\\n\\u003cbr /\\u003e\\n\\nAfter you create your bot, **copy the bot token and add it below**.","default":null,"optional":null,"type":"password"}]',
    categories: ['Communication'],
    featuredWeight: 1000000097,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: 'https://api.telegram.org',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_1lxhk1',
    nameSlug: 'google_drive',
    name: 'Google Drive',
    authType: 'oauth',
    description: 'Google Drive is a file storage and synchronization service which allows you to create and share your work online, and access your documents from anywhere.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_1lxhk1/logo/orig',
    customFieldsJson: '[]',
    categories: ['File Storage'],
    featuredWeight: 1000000096,
    connect: {
      allowed_domains: ['www.googleapis.com', 'drive.googleapis.com'],
      base_proxy_target_url: 'https://www.googleapis.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_X7LhNG',
    nameSlug: 'http',
    name: 'HTTP / Webhook',
    description: 'Get a unique URL where you can send HTTP or webhook requests',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_X7LhNG/logo/orig',
    customFieldsJson: '[]',
    categories: ['Infrastructure & Cloud'],
    featuredWeight: 1000000095,
    connect: {
      allowed_domains: ['pokeapi.co'],
      base_proxy_target_url: 'https://pokeapi.co',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_13Gh2V',
    nameSlug: 'google_calendar',
    name: 'Google Calendar',
    authType: 'oauth',
    description: 'With Google Calendar, you can quickly schedule meetings and events and get reminders about upcoming activities, so you always know what’s next. ',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_13Gh2V/logo/orig',
    customFieldsJson: '[]',
    categories: ['Productivity'],
    featuredWeight: 1000000094,
    connect: {
      allowed_domains: ['www.googleapis.com', 'calendar.googleapis.com'],
      base_proxy_target_url: 'https://www.googleapis.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_XaLhW4',
    nameSlug: 'schedule',
    name: 'Schedule',
    description: 'Trigger workflows on an interval or cron schedule.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_XaLhW4/logo/orig',
    customFieldsJson: '[]',
    categories: ['Productivity'],
    featuredWeight: 1000000094,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: null,
      proxy_enabled: false,
    },
  },
  {
    id: 'app_z6hGPq',
    nameSlug: 'pipedream_utils',
    name: 'Pipedream Utils',
    description: 'Utility functions to use within your Pipedream workflows',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_z6hGPq/logo/orig',
    customFieldsJson: '[]',
    categories: ['Infrastructure & Cloud'],
    featuredWeight: 1000000092,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: null,
      proxy_enabled: false,
    },
  },
  {
    id: 'app_qeh7a4',
    nameSlug: 'shopify_developer_app',
    name: 'Shopify',
    authType: 'keys',
    description:
      'Shopify is a complete commerce platform that lets anyone start, manage, and grow a business. You can use Shopify to build an online store, manage sales, market to customers, and accept payments in digital and physical locations.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_qeh7a4/logo/orig',
    customFieldsJson:
      '[{"name":"shop_id","label":"Shop ID","description":"If your store\'s URL is `https://acme-co.myshopify.com/`, your shop ID is `acme-co`","default":null,"optional":null,"enable_extract":null},{"name":"access_token","label":"Admin API Access Token","description":"Create a custom app in Shopify to obtain your Admin API access token. See [here for more info](https://pipedream.com/apps/shopify-developer-app#getting-started).","default":null,"optional":null,"type":"password"},{"name":"storefront_access_token","label":"Storefront API Access Token","description":"Follow the instructions [here](https://shopify.dev/docs/custom-storefronts/building-with-the-storefront-api/getting-started#step-1-enable-storefront-api-access) to enable Storefront API Access and generate your Storefront API Access token. ","default":null,"optional":true,"type":"password"}]',
    categories: ['Commerce'],
    featuredWeight: 1000000015,
    connect: {
      allowed_domains: ['myshopify.com'],
      base_proxy_target_url: 'https://{{custom_fields.shop_id}}.myshopify.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_1dBhP3',
    nameSlug: 'supabase',
    name: 'Supabase',
    authType: 'keys',
    description: 'Supabase is an open source Firebase alternative.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_1dBhP3/logo/orig',
    customFieldsJson:
      '[{"name":"subdomain","label":"Subdomain ID","description":"On Supabase, access Project Settings \\u003e Data API:\\n1. Copy the subdomain from the Project URL, if Project URL is `https://pipedream.supabase.co`, enter `pipedream` here.\\n2. Enable \\"Enable Data API\\" and make sure any schemas you need are added to the list of \'Exposed Schemas\'","default":null,"optional":null,"enable_extract":null},{"name":"service_key","label":"API Key","description":"On Supabase, access Project Settings \\u003e API Keys and copy your service_role key (Legacy API Keys) or Secret key (New API Keys) here","default":null,"optional":null,"type":"password"}]',
    categories: ['Databases'],
    featuredWeight: 1000000011,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: 'https://{{custom_fields.subdomain}}.supabase.co',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_1YMhwo',
    nameSlug: 'mysql',
    name: 'MySQL',
    authType: 'keys',
    description: 'MySQL is an open-source relational database management system.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_1YMhwo/logo/orig',
    customFieldsJson:
      '[{"name":"host","label":"Host","description":"The hostname or IP address of your MySQL server","default":null,"optional":null,"enable_extract":null},{"name":"port","label":"Port","description":"`3306`, unless you run MySQL on a different port","default":"3306","optional":null,"enable_extract":null},{"name":"username","label":"Username","description":"The account username to log in","default":null,"optional":null,"enable_extract":null},{"name":"database","label":"Database","description":"The name of the MySQL database to run queries against","default":null,"optional":null,"enable_extract":null},{"name":"use_pd_sql_proxy","label":"Use a shared static IP","description":"Enable requests from this database connection to originate from a shared static IP that you can add to your database allow-list.\\n\\n**Add this IP block to your database allow-list: `44.223.89.56/29`**","default":"true","optional":null,"type":"boolean"},{"name":"password","label":"Password","description":"The account password to log in","default":null,"optional":true,"type":"password"},{"name":"ca","label":"SSL CA Bundle","description":"The Certificate Authority text to use for the connection. E.g. (`-----BEGIN CERTIFICATE-----\\\\\\\\nMIIDBTCCAe2gAwIBAgIJA...`)","default":null,"optional":true,"enable_extract":true},{"name":"key","label":"SSL Private Key","description":"The key text to use for the connection. E.g. (`-----BEGIN PRIVATE KEY-----\\\\\\\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQ...`)","default":null,"optional":true,"enable_extract":true},{"name":"cert","label":"SSL Client Certificate","description":"The certificate text to use for the connection. E.g. (`-----BEGIN CERTIFICATE-----\\\\\\\\nMIIDBTCCAe2gAwIBAgIJA...`)","default":null,"optional":true,"enable_extract":true},{"name":"ssl_verification_mode","label":"SSL Verification Mode","description":"**Full Verification (default)**: Verifies that the server\'s SSL certificate is from a trusted Certificate Authority, and that the certificate\'s hostname matches the server you\'re connecting to.\\n\\n**Verify CA Certificate**: Verifies that the server\'s SSL certificate is signed by a trusted Certificate Authority.\\n\\n**Skip Verification**: Bypasses SSL certificate validation, which is not recommended. This can be useful for testing with self-signed certificates.","default":"verify_identity","optional":true,"type":"options","options":[{"label":"Full Verification","value":"verify_identity"},{"label":"Verify CA Certificate","value":"verify_ca"},{"label":"Skip Verification","value":"skip_verification"}]}]',
    categories: ['Databases'],
    featuredWeight: 1000000010,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: null,
      proxy_enabled: false,
    },
  },
  {
    id: 'app_1M0hNB',
    nameSlug: 'postgresql',
    name: 'PostgreSQL',
    authType: 'keys',
    description: 'PostgreSQL is a free and open-source relational database management system emphasizing extensibility and SQL compliance.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_1M0hNB/logo/orig',
    customFieldsJson:
      '[{"name":"host","label":"Host","description":"The hostname or IP address of your PostgreSQL server","default":null,"optional":null,"enable_extract":null},{"name":"port","label":"Port","description":"Typically `5432`, unless you run PostgreSQL on a different port","default":"5432","optional":null,"enable_extract":null},{"name":"user","label":"Username","description":"The account username to log in","default":null,"optional":null,"enable_extract":null},{"name":"password","label":"Password","description":"The account password to log in","default":null,"optional":null,"type":"password"},{"name":"database","label":"Database Name","description":"The name of the PostgreSQL database to run queries against","default":null,"optional":null,"enable_extract":null},{"name":"use_pd_sql_proxy","label":"Use Shared Static IP","description":"Enable requests from this database connection to originate from a shared static IP that you can add to your database allow-list.\\n\\n**Add this IP block to your database allow-list: `44.223.89.56/29`**","default":"true","optional":null,"type":"boolean"},{"name":"ssl_verification_mode","label":"SSL Verification Mode","description":"**Full Verification (default)**: Verifies that the server\'s SSL certificate is from a trusted Certificate Authority, and that the certificate\'s hostname matches the server you\'re connecting to.\\n\\n**Skip Verification**: Bypasses SSL certificate validation, which is not recommended. This can be useful for testing with self-signed certificates.","default":"verify_identity","optional":false,"type":"options","options":[{"label":"Full Verification","value":"verify_identity"},{"label":"Skip Verification","value":"skip_verification"}]},{"name":"ca","label":"SSL CA Bundle","description":"The Certificate Authority text to use for the connection. E.g. (`-----BEGIN CERTIFICATE-----\\\\\\\\nMIIDBTCCAe2gAwIBAgIJA...`)","default":null,"optional":true,"enable_extract":true},{"name":"key","label":"SSL Private Key","description":"The key text to use for the connection. E.g. (`-----BEGIN PRIVATE KEY-----\\\\\\\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQ...`)","default":null,"optional":true,"enable_extract":true},{"name":"cert","label":"SSL Client Certificate","description":"The certificate text to use for the connection. E.g. (`-----BEGIN CERTIFICATE-----\\\\\\\\nMIIDBTCCAe2gAwIBAgIJA...`)","default":null,"optional":true,"enable_extract":true},{"name":"pd_schema_explorer_retrieve_all","label":"Retreive All Schemas","description":"Defaults to only retrieving the `public` schema. If you need other schemas to be retrieved, set this value to `True`.","default":"false","optional":true,"type":"boolean"}]',
    categories: ['Databases'],
    featuredWeight: 1000000009,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: null,
      proxy_enabled: false,
    },
  },
  {
    id: 'app_Xe3hD1',
    nameSlug: 'aws',
    name: 'AWS',
    authType: 'keys',
    description: 'Amazon Web Services (AWS) offers reliable, scalable, and inexpensive cloud computing services.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_Xe3hD1/logo/orig',
    customFieldsJson:
      '[{"name":"accessKeyId","label":"Access Key ID","description":"Follow the [AWS Instructions](https://aws.amazon.com/premiumsupport/knowledge-center/create-access-key/) for creating an IAM user with an associated access and secret key. \\n\\nAs a best practice, attach the minimum set of IAM permissions necessary to perform the specific task.","default":null,"optional":null,"type":"password"},{"name":"secretAccessKey","label":"Secret Access Key","description":null,"default":null,"optional":null,"type":"password"}]',
    categories: ['Infrastructure & Cloud'],
    featuredWeight: 1000000008,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: null,
      proxy_enabled: false,
    },
  },
  {
    id: 'app_XKvh3O',
    nameSlug: 'sendgrid',
    name: 'Twilio SendGrid',
    authType: 'keys',
    description:
      'Send marketing and transactional email through the Twilio SendGrid platform with the Email API, proprietary mail transfer agent, and infrastructure for scalable delivery.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_XKvh3O/logo/orig',
    customFieldsJson:
      '[{"name":"api_key","label":"API Key","description":"Follow the instructions to [create an API key](https://docs.sendgrid.com/ui/account-and-settings/api-keys#creating-an-api-key) and enter it here.","default":null,"optional":null,"type":"password"}]',
    categories: ['Marketing'],
    featuredWeight: 1000000007,
    connect: {
      allowed_domains: ['api.sendgrid.com'],
      base_proxy_target_url: 'https://api.sendgrid.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_m5ghj5',
    nameSlug: 'amazon_ses',
    name: 'Amazon SES',
    authType: 'keys',
    description: 'Amazon SES is a cloud-based email service provider that can integrate into any application for high volume email automation',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_m5ghj5/logo/orig',
    customFieldsJson: '[{"name":"accessKeyId"},{"name":"secretAccessKey","type":"password"}]',
    categories: ['Communication'],
    featuredWeight: 1000000006,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: null,
      proxy_enabled: false,
    },
  },
  {
    id: 'app_X2Rhjl',
    nameSlug: 'klaviyo',
    name: 'Klaviyo',
    authType: 'keys',
    description: 'Klaviyo unifies your data, channels, and AI agents in one platform—text, WhatsApp, email marketing, and more—driving growth with every interaction.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_X2Rhjl/logo/orig',
    customFieldsJson:
      '[{"name":"api_key","label":"API Key","description":"- Private API Keys are available in [Settings \\u003e API keys](https://www.klaviyo.com/account#api-keys-tab). \\n- Read more about how Klaviyo private keys work in [their docs](https://developers.klaviyo.com/en/docs/retrieve_api_credentials#private-key).","default":null,"optional":null,"type":"password"}]',
    categories: ['Marketing'],
    featuredWeight: 1000000005,
    connect: {
      allowed_domains: ['a.klaviyo.com'],
      base_proxy_target_url: 'https:// https:',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_1pbhGX',
    nameSlug: 'zendesk',
    name: 'Zendesk',
    authType: 'oauth',
    description: 'Zendesk is award-winning customer service software trusted by 200K+ customers. Make customers happy via text, mobile, phone, email, live chat, social media.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_1pbhGX/logo/orig',
    customFieldsJson:
      '[{"name":"subdomain","label":"Subdomain","description":"If your Zendesk URL is `https://tango-charlie123.zendesk.com/`, enter `tango-charlie123` here.","default":null,"optional":null}]',
    categories: ['Help Desk & Support'],
    featuredWeight: 1000000004,
    connect: {
      allowed_domains: [],
      base_proxy_target_url: 'https://{{custom_fields.subdomain}}.zendesk.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_mvNhQa',
    nameSlug: 'servicenow',
    name: 'ServiceNow',
    authType: 'oauth',
    description: 'The smarter way to workflow',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_mvNhQa/logo/orig',
    customFieldsJson:
      '[{"name":"instance_name","label":"Instance Name","description":"The instance name is the host portion of your instance\'s URL: that is, the `dev123` in `https://dev123.service-now.com/`","default":null,"optional":null,"enable_extract":null},{"name":"client_id","label":"Client ID","description":"To generate your Client ID, sign in to your ServiceNow instance and go to **All** \\u003e **System OAuth** \\u003e **Inbound Integrations**. \\n- Click the **New Integration** button on the top right, select **OAuth - Authorization code grant** option from the pop up\\n- Your Client ID will be displayed in the following page\\n- Enter the below Redirect URI in your **New record** settings in the **Redirect URLs** field and click **Save**:\\n```https://api.pipedream.com/connect/oauth/oa_g2oiqA/callback```\\n- Make sure the option **This is a public client** option in unchecked","default":null,"optional":null,"enable_extract":null},{"name":"client_secret","label":"Client Secret","description":null,"default":null,"optional":null,"enable_extract":null}]',
    categories: ['Help Desk & Support'],
    featuredWeight: 1000000003,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: 'https://{{custom_fields.instance_name}}.service-now.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_M0hv7G',
    nameSlug: 'slack_v2',
    name: 'Slack',
    authType: 'oauth',
    description:
      'Slack is the AI-powered platform for work bringing all of your conversations, apps, and customers together in one place. Around the world, Slack is helping businesses of all sizes grow and send productivity through the roof.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_M0hv7G/logo/orig',
    customFieldsJson: '[]',
    categories: ['Communication'],
    featuredWeight: 1000000001,
    connect: {
      allowed_domains: ['slack.com', 'files.slack.com'],
      base_proxy_target_url: 'https://slack.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_1M0hlk',
    nameSlug: 'microsoft_teams',
    name: 'Microsoft Teams',
    authType: 'oauth',
    description: 'Microsoft Teams has communities, events, chats, channels, meetings, storage, tasks, and calendars in one place.',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_1M0hlk/logo/orig',
    customFieldsJson: '[]',
    categories: ['Communication'],
    featuredWeight: 1000000000,
    connect: {
      allowed_domains: ['graph.microsoft.com'],
      base_proxy_target_url: 'https://graph.microsoft.com',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_OrZhD7',
    nameSlug: 'salesforce_rest_api',
    name: 'Salesforce',
    authType: 'oauth',
    description:
      'Cloud-based customer relationship management (CRM) platform that helps businesses manage sales, marketing, customer support, and other business activities, ultimately aiming to improve customer relationships and streamline operations. ',
    imgSrc: 'https://assets.pipedream.net/s.v0/app_OrZhD7/logo/orig',
    customFieldsJson:
      '[{"name":"instancetype","label":"Instance Type","description":"In order to connect your Salesforce account, you must have a Salesforce Edition that has API Access. See [here](https://help.salesforce.com/s/articleView?id=000385436\\u0026type=1) for more details. Make sure to **[enable the Salesforce REST API](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_prereq.htm)** for your instance.\\n\\n**Editions with API Access:**\\n- Enterprise\\n- Unlimited\\n- Developer\\n- Performance","default":null,"optional":null,"type":"options","options":[{"label":"Production Instance","value":"https://login.salesforce.com"},{"label":"Sandbox Instance","value":"https://test.salesforce.com"}]}]',
    categories: ['CRM'],
    featuredWeight: 100000019,
    connect: {
      allowed_domains: null,
      base_proxy_target_url: 'https://{{custom_fields.instance_url}}',
      proxy_enabled: true,
    },
  },
  {
    id: 'app_OkrhlP',
    nameSlug: 'hubspot',
    name: 'HubSpot',
    authType: 'oauth',
    description: "HubSpot's CRM platform contains the marketing, sales, service, operations, and website-building software you need to grow your business.",
    imgSrc: 'https://assets.pipedream.net/s.v0/app_OkrhlP/logo/orig',
    customFieldsJson: '[]',
    categories: ['CRM'],
    featuredWeight: 100000018,
    connect: {
      allowed_domains: ['api.hubapi.com'],
      base_proxy_target_url: 'https://api.hubapi.com',
      proxy_enabled: true,
    },
  },
]
