FROM node:20-alpine AS development-dependencies-env
COPY . /app
WORKDIR /app
RUN npm ci

FROM node:20-alpine AS production-dependencies-env
COPY ./package.json package-lock.json /app/
WORKDIR /app
RUN npm ci --omit=dev

FROM node:20-alpine AS build-env
COPY . /app/
COPY --from=development-dependencies-env /app/node_modules /app/node_modules
WORKDIR /app
# Accept build args for Vite environment variables

ARG VITE_AIML_TOKEN
ARG VITE_ANTHROPIC_KEY
ARG VITE_API_URL
ARG VITE_APP_URL
ARG VITE_BFL_TOKEN
ARG VITE_GEMINI_API_KEY
ARG VITE_LOCAL_API_URL
ARG VITE_LOCAL_APP_URL
ARG VITE_NODE_ENV=production
ARG VITE_OPENAI_ADMIN_KEY
ARG VITE_OPENAI_KEY
ARG VITE_PIPEDREAM_CLIENT_ID
ARG VITE_PIPEDREAM_CLIENT_SECRET
ARG VITE_PIPEDREAM_ENVIRONMENT
ARG VITE_PIPEDREAM_PROJECT_ID
ARG VITE_RECRAFT_API_KEY
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_SERVICE_ROLE_KEY
ARG VITE_SUPABASE_URL
ARG VITE_TAVILY_API_KEY
ARG VITE_STRIPE_PUBLISHABLE_KEY
ARG VITE_STRIPE_SECRET_KEY
# Set them as env vars for the build
ENV VITE_AIML_TOKEN=$VITE_AIML_TOKEN
ENV VITE_ANTHROPIC_KEY=$VITE_ANTHROPIC_KEY
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_BFL_TOKEN=$VITE_BFL_TOKEN
ENV VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY
ENV VITE_LOCAL_API_URL=$VITE_LOCAL_API_URL
ENV VITE_LOCAL_APP_URL=$VITE_LOCAL_APP_URL
ENV VITE_NODE_ENV=$VITE_NODE_ENV
ENV VITE_OPENAI_ADMIN_KEY=$VITE_OPENAI_ADMIN_KEY
ENV VITE_OPENAI_KEY=$VITE_OPENAI_KEY
ENV VITE_PIPEDREAM_CLIENT_ID=$VITE_PIPEDREAM_CLIENT_ID
ENV VITE_PIPEDREAM_CLIENT_SECRET=$VITE_PIPEDREAM_CLIENT_SECRET
ENV VITE_PIPEDREAM_ENVIRONMENT=$VITE_PIPEDREAM_ENVIRONMENT
ENV VITE_PIPEDREAM_PROJECT_ID=$VITE_PIPEDREAM_PROJECT_ID
ENV VITE_RECRAFT_API_KEY=$VITE_RECRAFT_API_KEY
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_SERVICE_ROLE_KEY=$VITE_SUPABASE_SERVICE_ROLE_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_TAVILY_API_KEY=$VITE_TAVILY_API_KEY
ENV VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY
ENV VITE_STRIPE_SECRET_KEY=$VITE_STRIPE_SECRET_KEY
RUN npm run build

FROM node:20-alpine
COPY ./package.json package-lock.json /app/
COPY --from=production-dependencies-env /app/node_modules /app/node_modules
COPY --from=build-env /app/build /app/build
WORKDIR /app
CMD ["npm", "run", "start"]